fos_rest:
    param_fetcher_listener: true
    body_listener: true
    view:
        view_response_listener: 'force'
    format_listener:
        rules:
            prefer_extension: false
            fallback_format: json
